### ISSUE TITLE
JS style guide: Formatting ternary expressions

### ISSUE THREAD

**Issue by jzaefferer** [jquery/contribute.jquery.org#45]
We don't have rules on how to format ternary expressions. Accordingly we have quite a few styles for these:

``` js
// from core/css.js
// inline
parts = typeof value === "string" ? value.split(" ") : [ value ];

// from core/css.js
// line break after question mark and colon:
return rnumnonpx.test( computed ) ?
    jQuery( elem ).position()[ prop ] + "px" :
    computed;

// from ui/jquery.ui.progressbar.js
// line break after colon:
return this.indeterminate ? false :
            Math.min( this.options.max, Math.max( this.min, newValue ) );
```

There's probably more variations.

@dmethvin @scottgonzalez @gibson042 do you have preferences on any of these?

**Comment by TemporalFuzz** [comment]
I usually prefer the first, but the second is more clear for comments if you're documenting all of it.

**Comment by nordfjord** [comment]
You've left out a 4th option.

I'm commenting here because this was the top result when googling "Javascript ternary formatting"

```js
parts = typeof value === "string" 
  ? value.split(" ")
  : [ value ];
```

**Comment by Made-of-Clay** [comment]
Following up a bit late in the conversation, I had a discussion with a co-worker on why to choose @nordfjord's 4th option vs @jzaefferer's 2nd option. It came down to how the author interprets the meaning of ? and : in the expression.

**4th Option**
My preferred style, the ? and : are viewed as the beginnings of the `if` and `else` statements respectively.

**2nd Option**
My co-workers style, the ? and : are viewed as the *endings* of the condition and `if` statement respectively, while the ; marks both the end of the `else` statement and the end of the ternary itself.

Understanding this now, I am more accepting of either style, despite preferring the 4th option; I like the 4th because the symbols basically introduce the beginning of the differences. That is particularly helpful when the `if`/`else` statements become complex or long.

And that's my 2.5-years-after-the-fact note. Happy dev-ing!
